addSbtPlugin("org.scala-js"      % "sbt-scalajs" % "0.6.22")
addSbtPlugin("de.heikoseeberger" % "sbt-header"  % "5.0.0")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.7")
addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.5.3")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "1.0.0")