addSbtPlugin("org.scala-js"      % "sbt-scalajs" % "0.6.11")
addSbtPlugin("de.heikoseeberger" % "sbt-header"  % "1.6.0")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.3")
addSbtPlugin("me.lessis"         % "bintray-sbt" % "0.3.0")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "0.8.0")